force-app/main/default/objects/IntegrationFieldMapping__mdt/IntegrationFieldMapping__mdt.object-meta.xml
<CustomObject>
    <label>Integration Field Mapping</label>
    <pluralLabel>Integration Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationFieldMapping__mdt/fields/APIAttributeName__c.field-meta.xml
<CustomField>
    <fullName>APIAttributeName__c</fullName>
    <label>API Attribute Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationFieldMapping__mdt/fields/DefaultValue__c.field-meta.xml
<CustomField>
    <fullName>DefaultValue__c</fullName>
    <label>Default Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationFieldMapping__mdt/fields/FieldAPIname__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIname__c</fullName>
    <label>Salesforce field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationFieldMapping__mdt/fields/IntegrationStream__c.field-meta.xml
<CustomField>
    <fullName>IntegrationStream__c</fullName>
    <label>Integration Stream</label>
    <referenceTo>IntegrationStream__mdt</referenceTo>
    <relationshipLabel>Integration Field Mappings</relationshipLabel>
    <relationshipName>IntegrationFieldMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IntegrationFieldMapping__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IntegrationStream__mdt/IntegrationStream__mdt.object-meta.xml
<CustomObject>
    <label>Integration Stream</label>
    <pluralLabel>Integration Stream</pluralLabel>
</CustomObject>

force-app/main/default/classes/IntgerationRequestGenerator.cls
public class IntgerationRequestGenerator {

    public static string getXML(String bizStrem,Id accountId){
        
        //Custom metadata types 
        IntegrationStream__mdt intgRec = [Select Id,(Select Id,FieldAPIname__c,APIAttributeName__c,DefaultValue__c from IntegrationFieldMappings__r 
                                                 where IsActive__c =TRUE ) 
                                                 from IntegrationStream__mdt where DeveloperName=:bizStrem Limit 1];
        
        //Account data
        Account acc = [Select Id,Name,Phone,SLA__c from Account where Id=:accountId];
        sObject objRec = (sObject)acc;
        
        //XML Writer             
        XmlStreamWriter  w= new XmlStreamWriter();
        w.writeStartElement(null,'Accounts',null);
        
        for(IntegrationFieldMapping__mdt fieldMap : intgRec.IntegrationFieldMappings__r){
            
            String fieldVal = ( fieldMap.DefaultValue__c != NULL ? fieldMap.DefaultValue__c : (string) objRec.get(fieldMap.FieldAPIname__c));
            
            w.writeStartElement(null, fieldMap.APIAttributeName__c ,null);
            w.writeCharacters(  (fieldVal == null ? '' : fieldVal ) );
            w.writeEndElement();
        }
        
        w.writeEndElement();
        
       /* XmlStreamWriter  w= new XmlStreamWriter();
        w.writeStartElement(null, 'User',null );
        w.writeNamespace('i','http://temp.blogspot.com');
        w.writeStartElement(null,'DisplayName',null);
        w.writeCharacters('Unid');
        w.writeEndElement();
        w.writeEndElement();
         
        return w.getXmlString(); */
        
        return w.getXmlString();
    }
    
    public static string getJSON(){
        
        return '';
    }
}